---
name: Go-Build-Lint-Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  golangci:
    name: Build-Lint-Test
    runs-on: ubuntu-latest
    env:
      DPDK_VERSION: 22.07
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate cache keys
        id: get_ref_keys
        run: |
          echo "ccache=ccache-dpdk-${{ env.DPDK_VERSION }}" >> "$GITHUB_OUTPUT"
      - name: Retrieve ccache cache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ steps.get_ref_keys.outputs.ccache }}-${{ github.run_id }}
          restore-keys: 
            ${{ steps.get_ref_keys.outputs.ccache }}-
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Set DPDK location
        run: |
          echo "DPDK_HOME=$GITHUB_WORKSPACE/dpdk" >> "$GITHUB_ENV"
      - name: build-dpdk
        run: |
          cd build/dpdk
          ./install.sh
          cd ~
      - name: print-ccache-stats
        run: ccache -s
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
      - name: Build-dpdkinfra
        run: go build -v ./cmd/dpdkinfra/...
      - name: Test
        run: go test -v -coverprofile=profile.cov ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov